<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="averageService"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:req="http://nl.hu.iac/averageservice/request" xmlns:rsp="http://nl.hu.iac/averageservice/response"
	xmlns:flt="http://nl.hu.iac/averageservice/fault" xmlns="http://nl.hu.iac/averageservice/"
	targetNamespace="http://nl.hu.iac/averageservice/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://nl.hu.iac/averageservice/request"
				schemaLocation="request.xsd" />
			<xsd:import namespace="http://nl.hu.iac/averageservice/response"
				schemaLocation="response.xsd" />
			<xsd:import namespace="http://nl.hu.iac/averageservice/fault"
				schemaLocation="fault.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="request">
		<wsdl:part name="request" element="req:averageRequest" />
	</wsdl:message>
	<wsdl:message name="response">
		<wsdl:part name="response" element="rsp:averageResponse" />
	</wsdl:message>
	<wsdl:message name="fault">
		<wsdl:part name="fault" element="flt:averageFault" />
	</wsdl:message>
	<wsdl:portType name="averageServiceInterface">
		<wsdl:operation name="calculateaverage">
			<wsdl:input message="request" />
			<wsdl:output message="response" />
			<wsdl:fault name="fault" message="fault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="averageServiceBinding" type="averageServiceInterface">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="calculateaverage">
			<soap:operation soapAction="" style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">
				<soap:fault name="fault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="averageServiceService">
		<wsdl:port name="WS-Port" binding="averageServiceBinding">
			<soap:address location="http://localhost:8080/ws-producer/soap" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>